Quest.create([
  {name: "Cook's Assistant"},
  {name: "Demon Slayer"},
  {name: "The Restless Ghost"},
  {name: "Romeo & Juliet"},
  {name: "Sheep Shearer"},
  {name: "Shield of Arrav"},
  {name: "Ernest the Chicken"},
  {name: "Vampyre Slayer"},
  {name: "Imp Catcher"},
  {name: "Prince Ali Rescue"},
  {name: "Doric's Quest"},
  {name: "Black Knights' Fortress"},
  {name: "Witch's Potion"},
  {name: "The Knight's Sword"},
  {name: "Goblin Diplomacy"},
  {name: "Pirate's Treasure"},
  {name: "Dragon Slayer"},
  {name: "Druidic Ritual"},
  {name: "Lost City"},
  {name: "Witch's House"},
  {name: "Merlin's Crystal"},
  {name: "Heroes' Quest"},
  {name: "Scorpion Catcher"},
  {name: "Family Crest"},
  {name: "Tribal Totem"},
  {name: "Fishing Contest"},
  {name: "Monk's Friend"},
  {name: "Temple of Ikov"},
  {name: "Clock Tower"},
  {name: "Holy Grail"},
  {name: "Tree Gnome Village"},
  {name: "Fight Arena"},
  {name: "Hazeel Cult"},
  {name: "Sheep Herder"},
  {name: "Plague City"},
  {name: "Sea Slug"},
  {name: "Waterfall Quest"},
  {name: "Biohazard"},
  {name: "Jungle Potion"},
  {name: "The Grand Tree"},
  {name: "Shilo Village"},
  {name: "Underground Pass"},
  {name: "Observatory Quest"},
  {name: "The Tourist Trap"},
  {name: "Watchtower"},
  {name: "Dwarf Cannon"},
  {name: "Murder Mystery"},
  {name: "The Dig Site"},
  {name: "Gertrude's Cat"},
  {name: "Legends' Quest"},
  {name: "Rune Mysteries"},
  {name: "Big Chompy Bird Hunting"},
  {name: "Elemental Workshop I"},
  {name: "Priest in Peril"},
  {name: "Nature Spirit"},
  {name: "Death Plateau"},
  {name: "Troll Stronghold"},
  {name: "Tai Bwo Wannai Trio"},
  {name: "Regicide"},
  {name: "Eadgar's Ruse"},
  {name: "Shades of Mort'ton"},
  {name: "The Fremennik Trials"},
  {name: "Horror from the Deep"},
  {name: "Throne of Miscellania"},
  {name: "Monkey Madness I"},
  {name: "Haunted Mine"},
  {name: "Troll Romance"},
  {name: "In Search of the Myreque"},
  {name: "Creature of Fenkenstrain"},
  {name: "Roving Elves"},
  {name: "Ghosts Ahoy"},
  {name: "One Small Favour"},
  {name: "Mountain Daughter"},
  {name: "Between a Rock..."},
  {name: "The Feud"},
  {name: "The Golem"},
  {name: "Desert Treasure"},
  {name: "Icthlarin's Little Helper"},
  {name: "Tears of Guthix"},
  {name: "Zogre Flesh Eaters"},
  {name: "The Lost Tribe"},
  {name: "The Giant Dwarf"},
  {name: "Recruitment Drive"},
  {name: "Mourning's End Part I"},
  {name: "Forgettable Tale..."},
  {name: "Garden of Tranquillity"},
  {name: "A Tail of Two Cats"},
  {name: "Wanted!"},
  {name: "Mourning's End Part II"},
  {name: "Rum Deal"},
  {name: "Shadow of the Storm"},
  {name: "Making History"},
  {name: "Ratcatchers"},
  {name: "Spirits of the Elid"},
  {name: "Devious Minds"},
  {name: "The Hand in the Sand"},
  {name: "Enakhra's Lament"},
  {name: "Cabin Fever"},
  {name: "Fairytale I - Growing Pains"},
  {name: "Recipe for Disaster"},
  {name: "In Aid of the Myreque"},
  {name: "A Soul's Bane"},
  {name: "Rag and Bone Man"},
  {name: "Rag and Bone Man II"},
  {name: "Swan Song"},
  {name: "Royal Trouble"},
  {name: "Death to the Dorgeshuun"},
  {name: "Fairytale II - Cure a Queen"},
  {name: "Lunar Diplomacy"},
  {name: "The Eyes of Glouphrie"},
  {name: "Darkness of Hallowvale"},
  {name: "The Slug Menace"},
  {name: "Elemental Workshop II"},
  {name: "My Arm's Big Adventure"},
  {name: "Enlightened Journey"},
  {name: "Eagles' Peak"},
  {name: "Animal Magnetism"},
  {name: "Contact!"},
  {name: "Cold War"},
  {name: "The Fremennik Isles"},
  {name: "Tower of Life"},
  {name: "The Great Brain Robbery"},
  {name: "What Lies Below"},
  {name: "Olaf's Quest"},
  {name: "Another Slice of H.A.M."},
  {name: "Dream Mentor"},
  {name: "Grim Tales"},
  {name: "King's Ransom"},
  {name: "Monkey Madness II"},
  {name: "Misthalin Mystery"},
  {name: "Client of Kourend"},
  {name: "Bone Voyage"},
  {name: "The Queen of Thieves"},
  {name: "The Depths of Despair"},
  {name: "The Corsair Curse"},
  {name: "Dragon Slayer II"},
  {name: "Tale of the Righteous"},
  {name: "A Taste of Hope"},
  {name: "Making Friends with My Arm"},
  {name: "The Forsaken Tower"},
  {name: "The Ascent of Arceuus"},
  {name: "X Marks the Spot"},
  {name: "Song of the Elves"},
  {name: "The Fremennik Exiles"},
  {name: "Sins of the Father"}
])